      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Polinize idéias</h2>
          <p>O Projeto <b>Pólen</b> é uma plataforma livre para o desenvolvimento
          de aplicações que se autenticam na Coolmeia</p>
          <p><a class="btn btn-warning" href="#" role="button">Polenize &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Estenda a Coolmeia</h2>
          <p>Crie suas próprias aplicações sociais baseadas na rede social Coolmeia</p>
          <p><a class="btn btn-warning" href="#" role="button">Baixe o código &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Crie sua iniciativa</h2>
          <p>Contribua com seu 1% de iniciativa, dedique algum tempo.</p>
          <p><a class="btn btn-warning" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>