<?php if($this->configs): ?>

<div class="jumbotron">
  <div id="config_img">
    <img src="/store/<?php echo $this->logo; ?>" alt="..." class="img-rounded"> 
  </div>  
  <h1 class="config_titulo"> <?php echo $this->titulo; ?></h1>
  <div id="config_descricao">
    <?php echo $this->descricao; ?>
  </div>
    <p></p>
</div>


<?php else : ?>

      <div class="jumbotron">
        <div class="container">
          <h2>Seja bem-vindo</h2>
          <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
          <p><a class="btn btn-warning btn-lg" role="button">Learn more &raquo;</a></p>
        </div>
      </div>

       <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Polinize idéias</h2>
          <p>O Projeto <b>Pólen</b> é uma plataforma livre para o desenvolvimento
          de aplicações que se autenticam na Coolmeia</p>
          <p><a class="btn btn-warning" href="#" role="button">Polenize &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Estenda a Coolmeia</h2>
          <p>Crie suas próprias aplicações sociais baseadas na rede social Coolmeia</p>
          <p><a class="btn btn-warning" href="#" role="button">Baixe o código &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Crie sua iniciativa</h2>
          <p>Contribua com seu 1% de iniciativa, dedique algum tempo.</p>
          <p><a class="btn btn-warning" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

<?php endif; ?>

