<h2>Administração do Polen</h2>

<hr />

<nav class="navbar" role="navigation">
	<a href="/admin/polen/configurar/" class="btn btn-warning navbar-btn ">
		<i class="glyphicon glyphicon-cog"> Configurar</i>
	</a>
	<a href="/admin/polen/modulos/" class="btn btn-default navbar-btn">
		<i class="glyphicon glyphicon-cloud-upload"> Módulos</i>
	</a>
</nav>


<table class="table table-striped">
  <thead>
	  <tr>
	  	<td>Item</td>
	  	<td></td>
	  </tr>
  </thead>
  <tbody>
	  <tr>
	  	<td>Logo</td>
	  	<td><img src="/img/logo-polen.png" /></td>
	  </tr>
	  <tr>
	  	<td>Título</td>
	  	<td>Plante sua Salcinha</td>
	  </tr>  
	  <tr>
	  	<td>Descrição</td>
	  	<td>Blah blah bçah</td>
	  </tr>
  </tbody>
</table>
